### PR TITLE
Run latest versions of test suites

### PR DESCRIPTION
**Pull request by michielbdejong**
Depends on https://github.com/pdsinterop/php-solid-auth/pull/18

### CODE REVIEW

**Comment by michielbdejong** [comment]
Tests are failing due to https://github.com/pdsinterop/php-solid-server/issues/54 - will add a SKIP_CONC env var to solid-crud-tests.

**Comment by michielbdejong** [comment]
Hm, that's odd, in github actions it's getting the cookie correctly but then still can't seem to use it successfully when running the solid-crud-tests. Re-running to see if this problem is intermittent, or related to some difference between my test server and the github actions execution environment.

**Comment by Potherca** [comment]
https://github.com/pdsinterop/php-solid-auth/pull/18 has been merged and released as pdsinterop/solid-auth:v0.6.2

**Comment by Potherca** [comment]
I've rebased this MR on the recent changes on `main` (mostly bug fixes) to see if/what changes in the checks.

**Review by Potherca — APPROVED** [review]

**Comment by Potherca** [comment]
Yeah, there definitely something going on with GitHub Action... Getting intermittent timeouts now as well... We might have to reconsider how the tests are currently run and/or split the actions across multiple jobs.

**Comment by Potherca** [comment]
Merging this in order to keep things moving. Subsequent fixes to get the build passing can be added in later MRs. (I want to get the `v0.6` release out of the door, so I can start adding the Link Metadata feature).

**Pull request merged**
